### ISSUE TITLE
wrong cmd in help and readme.md, path required

### ISSUE THREAD

**Issue by RalMay** [Proteus1989/Air-Explorer-Decrypter-Simple-Client#1]
Hi and thx for a helpful tool!

3 issues in Win10 x64:

1. program help and readme.md feature wrong syntax, it must be _java.exe **-jar** airexplorerdecryptersimpleclient.jar -p=pass .\infile1 ..._  (so the "-jar" must be _before_ the *.jar file to execute)

2. _infile_ reguires a path (e.g. _.\infile_), when just trying to decrypt from current directory error _java.lang.NullPointerException: Cannot invoke "java.io.File.getPath()" because the return value of "java.io.File.getParentFile()" is null_ is thrown

3. parameter _-g_ (_java.exe -jar airexplorerdecryptersimpleclient.jar -g_) doesn't open a GUI but throws error _Missing required options and parameters: '--password=\<password>', '\<file>'_

HTH!

**Comment by Proteus1989** [comment]
Thanks for your useful comments. I'm fix them all 👍

**Comment by Proteus1989** [comment]
Fixed in release version [v2.0.1](https://github.com/Proteus1989/Air-Explorer-Decrypter-Simple-Client/releases/tag/v2.0.1)

**Comment by RalMay** [comment]
Thank you very much, but 2.0.1 just throws another error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Program Files\Java\jdk-19\bin\awt.dll: Can't load this .dll (machine code=0x0) on a AMD 64-bit platform

Details:
[airexplorerdecryptersimpleclient-2.0.1.jar_error.txt](https://github.com/Proteus1989/Air-Explorer-Decrypter-Simple-Client/files/10729224/airexplorerdecryptersimpleclient-2.0.1.jar_error.txt)

better readable (and full) log in free [Sysinternals Procmon](https://live.sysinternals.com/Procmon64.exe) format:
[airexplorerdecryptersimpleclient-2.0.1.jar_error.PML.zip](https://github.com/Proteus1989/Air-Explorer-Decrypter-Simple-Client/files/10729251/airexplorerdecryptersimpleclient-2.0.1.jar_error.PML.zip)


edit:
BTW: I guess our main concern was not to be able to decrypt encrypted files when Airexplorer went out of business.
Support told me (and I tested it to be true even on a new/fresh system) that the _free_ version of AE does _de​​crypt_ (just not _encrypt_) files and folders well.
It's surely not wrong to have your great tool as a 2nd option though.

**Comment by Proteus1989** [comment]
Hello, @RalMay,
Unfortunately, that issue seems more related to the current setup in your local machine. As you can read in [this link](https://youtrack.jetbrains.com/issue/IDEA-259821), it could be caused due `a corrupted Windows installation`.
